### ISSUE TITLE
Error when using yarn

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [Angelillo15/MinecraftPurpleTheme#4]
https://github.com/Angelillo15/IceMinecraftTheme/issues/4 The command from this issue was used
![изображение](https://github.com/Angelillo15/MinecraftPurpleTheme/assets/68144848/fdc6a748-abf8-4ff5-bee2-f81dcd67255f)
and plus site after usind command 
![изображение](https://github.com/Angelillo15/MinecraftPurpleTheme/assets/68144848/9f59738b-aa93-44f0-a4cb-52ed3561a2e9)

**Comment by Angelillo15** [comment]
You have to do
```sh
yarn build:production
```

In /var/www/pterodactyl
